#!/bin/sh
if [ -n "$DEBUG" ]; then
    set -x
fi

mkdir /root/.ssh
cp /etc/secrets-mount/* /root/.ssh
chown root:root /root/.ssh
chmod 600 /root/.ssh/*

PULL_CMD="GIT_SSH_COMMAND=\"ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no\" git pull --recurse-submodules"
CLONE_CMD="GIT_SSH_COMMAND=\"ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no\" git clone --recurse-submodules --single-branch --branch ${GIT_SYNC_BRANCH} ${GIT_SYNC_REPO} ${GIT_SYNC_DEST}"
UPDATE_CMD="GIT_SSH_COMMAND=\"ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no\" git remote update"


if [ -n "$GIT_SYNC_ROOT" ]; then
    cd $GIT_SYNC_ROOT
fi

if [ -d "$GIT_SYNC_DEST" ]; then
  cd $GIT_SYNC_DEST
else
  eval $CLONE_CMD
  cd $GIT_SYNC_DEST
fi

while : ; do
  eval $UPDATE_CMD
  if [ $(git rev-parse --abbrev-ref HEAD) != $GIT_SYNC_BRANCH ]; then
    echo -e New version found!
    eval $PULL_CMD
  fi
  sleep 10
done
