#!/bin/sh
if [ -n "$DEBUG" ]; then
    set -x
fi

GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
PULL_CMD="$GIT_SSH_COMMAND git pull ${GIT_SYNC_REPO} ${GIT_SYNC_BRANCH} --recurse-submodules"

if [ -n "$GIT_SYNC_ROOT" ]; then
    cd $GIT_SYNC_ROOT
fi

if [ -d "$GIT_SYNC_DEST" ]; then
  cd $GIT_SYNC_DEST
else
  mkdir $GIT_SYNC_DEST
  cd $GIT_SYNC_DEST
  git init
fi

while : ; do
  git remote update
  if [ $(git rev-parse --abbrev-ref HEAD) != "master" ]; then
    echo -e New version found!
    eval $PULL_CMD
  fi
  sleep 1
done
